#!/bin/sh

# Source lemonbar config
. $HOME/.config/lemonbar/lemonbar_config

# Override Panel Settings
PW=180
PH=70
PX=1176
PY=78

# Settings for n30f for fancy look
n30f -d -x 1176 -y 48 /home/dead/.config/popups/power/bg.png &


echo " %{F$RED}%{F-} %{A:s:}Suspend%{A}  %{F$BLUE} %{F-}%{A:l:}Lock%{A} %{F$MAGENTA} %{F-}%{A:e:}Exit%{A}" | lemonbar -g ${PW}x${PH}+${PX}+${PY} -f "$FONT1" -f "$FONT3" -B "$BG" -F "$FG" -dp | \
    while :; do
        read line
        case $line in
            'e')
                p=$(pgrep -n lemonbar)
                n=$(pgrep -n n30f)
                kill $n
                kill $p
                exit
                ;;
            'l')
                i3lock-fancy &
                p=$(pgrep -n lemonbar)
                n=$(pgrep -n n30f)
                kill $n
                kill $p
                exit
                ;;
            's')
                systemctl suspend
                p=$(pgrep -n lemonbar)
                n=$(pgrep -n n30f)
                kill $n
                kill $p
                exit
                ;;
        esac
    done
