#!/bin/bash
clear
# a system info script written by yours truly
# it's hardcoded stuff, lulz

red="\e[31m"
grn="\e[32m"
ylw="\e[33m"
cyn="\e[36m"
blu="\e[34m"
prp="\e[35m"
bprp="\e[35;1m"
rst="\e[0m"
blk="\e[30m"

color-echo()
{  # print with colors
  echo -e " $red$1  $rst$2"
}

# ascii art
echo
echo -e "         "

# optional blocks
if  [[ $1 = "-b" ]]; then
 pcs() { for i in {0..7}; do echo -en "\e[${1}$((30+$i))m \u2588\u2588 \e[0m"; done; }
 printf "\n%s\n%s\n\n" "$(pcs)" "$(pcs '1;')"
else
 :
fi

echo -e "\n"

for i in {0..7}; do echo -en "\e[$((30+$i))m ${colors[i]} \u2588\u2588 \e[0m"; done

echo -e "\n"

# ascii art
echo
echo -e "         "

echo
echo
echo
