# background and foreground MUST exist and MUST be hex color values
# names cannot contain '-'
terminal:
    background: ""
    foreground: ""
    bold: ""
    termbackground: ""
    font: "Anonymice Nerd Font 10"
    colors: ["", "", "", "", "", "", "", "", ""]
    # colors  0=black     1=red     2=green   3=yellow    4=blue    5=purple    6=cyan     7=grey     8=white

border:
    pixels: 2
    all: 0
    top: 0
    bottom: 0
    color: ""


gap:
    inner: 20
    outer: 0


bar:
    height: 20
    width: "100%"
    radius: 0
    bottom: "false"
    background: ""
    font0: "DejaVu Sans Mono:size=10:antialias=false;2"


